[package]
name = "anagram"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.26"
itertools = "0.14.0"
substring = "1.4.5"
rayon = "1.5"
